# Generated by Django 5.2.7 on 2026-01-21 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumSignalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(help_text='Firebase document ID', max_length=255, unique=True)),
                ('firebase_user_id', models.CharField(blank=True, help_text='Firebase user ID', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('signal_type', models.CharField(blank=True, max_length=100)),
                ('subscription_period', models.CharField(blank=True, max_length=50)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Premium Signal Payment',
                'verbose_name_plural': 'Premium Signal Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(help_text='Firebase document ID', max_length=255, unique=True)),
                ('firebase_user_id', models.CharField(blank=True, help_text='Firebase user ID', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='SignalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(help_text='Firebase document ID', max_length=255, unique=True)),
                ('firebase_user_id', models.CharField(blank=True, help_text='Firebase user ID', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('notification_type', models.CharField(blank=True, max_length=100)),
                ('signal_data', models.JSONField(blank=True, help_text='Signal details as JSON', null=True)),
                ('read', models.BooleanField(default=False)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('notification_date', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal Notification',
                'verbose_name_plural': 'Signal Notifications',
                'ordering': ['-notification_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_id', models.CharField(help_text='Firebase document ID', max_length=255, unique=True)),
                ('firebase_user_id', models.CharField(blank=True, help_text='Firebase user ID', max_length=255)),
                ('completed_videos', models.JSONField(blank=True, help_text='List of completed video IDs', null=True)),
                ('video_durations', models.JSONField(blank=True, help_text='Video durations data', null=True)),
                ('total_completed', models.IntegerField(default=0)),
                ('progress_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
                'ordering': ['-last_activity'],
            },
        ),
    ]
